sudo: required

os: "linux"
dist: "trusty"
language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

install:
  - docker login --username=_ --password=${HEROKU_TOKEN} registry.heroku.com
  - docker build -t local/instronizer .
  - docker tag local/instronizer:latest registry.heroku.com/instronizer/web;
  - docker images
  - docker push registry.heroku.com/instronizer/web



#  - heroku container:push instronizer