sudo: required
os: linux
dist: trusty
addons:
  apt:
    packages:
    - docker-ce
services:
- docker
deploy:
  provider: heroku
  api_key:
    secure: t3XG8PqsuBxUvCm8QoIHV5kmNid5RRm61i0kyQkfTNYSGBfP8NvYSSmZrm6ah1KAKPEbjNaepqaqVg3F94BcVKS2Chm3cld8EZwvNa8MRE1M5tQZ/fK3/n0QsXi3FreAWatdA1T5giyxs/wwRS9dJ8q6xECDgOYUtxlDBW7xy9KaHuSgkegJovpPdQKAsb+1Q09sn1/BBDv6IOLM+0SFxej+73XXsBxVGyP471URA8QIKPVm/OkwavVrpUP2QQn42n7v1TaIj3tXgG5t0sYCIpxzMm7Rmq92krZF8PyujShRJWC3taDDcrqUYhfRvr49uNXuuFzQ6aZwwFJ6/DIdglHTBzS8Yxlvlwdmmm1kLtspLYG6xZJ4hkMiFDF9NKFjqrLgU127xRYfVODL33GyI/97YjGyNxJBqAvZSx4IbRjFcHX9u5g8UEajmCJ8W5CmrEL48Gbx2boDD/B+ZBINdT6bdg8ALq6OTleO2ueJmJM6I/4VrTDw9rSP0KX9SiB1xccZ14uRNMPJY2m1k0Sn4zRxPibSNeujRe+rYl9juDv9vvttzdLrp35XEBW5npg8LqtiFhfpaHnOxAK9b+Kpl9exGgB+t1GQxR0t/fPXqns4X9kWJ5a92pqS0JL+RouKtPrmCrn5cikbCbDkzCrBFDftpyHFGlhr/Ss/Lop2rjI=
  app: instrumentalists-dnn
  on:
    repo: micmarty/instrument-classifier-polyphonic
    branch: travis/deployment-test
script:
- docker login --username=${DOCKER_USERNEME} --password=${DOCKER_PASSWORD}
- docker build -t local/instronizer .
- docker tag local/instronizer:latest micmarty/instronizer;
- docker images
after_success:
- docker push micmarty/instronizer

